#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: 750e50d
#
# Source0 file verified with key 0x41633B9FE837F581 (vapier@gentoo.org)
#
%define keepstatic 1
Name     : attr
Version  : 2.5.2
Release  : 49
URL      : https://download-mirror.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz
Source0  : https://download-mirror.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz
Source1  : https://download-mirror.savannah.gnu.org/releases/attr/attr-2.5.2.tar.gz.sig
Summary  : A library for filesystem extended attribute support
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+ LGPL-2.1
Requires: attr-bin = %{version}-%{release}
Requires: attr-lib = %{version}-%{release}
Requires: attr-license = %{version}-%{release}
Requires: attr-locales = %{version}-%{release}
Requires: attr-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-expected-result-for-a-setfattr-test.patch

%description
_________________________________
Package home: https://savannah.nongnu.org/projects/attr

%package bin
Summary: bin components for the attr package.
Group: Binaries
Requires: attr-license = %{version}-%{release}

%description bin
bin components for the attr package.


%package dev
Summary: dev components for the attr package.
Group: Development
Requires: attr-lib = %{version}-%{release}
Requires: attr-bin = %{version}-%{release}
Provides: attr-devel = %{version}-%{release}
Requires: attr = %{version}-%{release}

%description dev
dev components for the attr package.


%package dev32
Summary: dev32 components for the attr package.
Group: Default
Requires: attr-lib32 = %{version}-%{release}
Requires: attr-bin = %{version}-%{release}
Requires: attr-dev = %{version}-%{release}

%description dev32
dev32 components for the attr package.


%package doc
Summary: doc components for the attr package.
Group: Documentation
Requires: attr-man = %{version}-%{release}

%description doc
doc components for the attr package.


%package lib
Summary: lib components for the attr package.
Group: Libraries
Requires: attr-license = %{version}-%{release}

%description lib
lib components for the attr package.


%package lib32
Summary: lib32 components for the attr package.
Group: Default
Requires: attr-license = %{version}-%{release}

%description lib32
lib32 components for the attr package.


%package license
Summary: license components for the attr package.
Group: Default

%description license
license components for the attr package.


%package locales
Summary: locales components for the attr package.
Group: Default

%description locales
locales components for the attr package.


%package man
Summary: man components for the attr package.
Group: Default

%description man
man components for the attr package.


%package staticdev
Summary: staticdev components for the attr package.
Group: Default
Requires: attr-dev = %{version}-%{release}

%description staticdev
staticdev components for the attr package.


%package staticdev32
Summary: staticdev32 components for the attr package.
Group: Default
Requires: attr-dev = %{version}-%{release}

%description staticdev32
staticdev32 components for the attr package.


%prep
%setup -q -n attr-2.5.2
cd %{_builddir}/attr-2.5.2
%patch -P 1 -p1
pushd ..
cp -a attr-2.5.2 build32
popd
pushd ..
cp -a attr-2.5.2 buildavx2
popd
pushd ..
cp -a attr-2.5.2 buildapx
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707073073
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure  INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--enable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure  INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--enable-static   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure  INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--enable-static
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildapx/
CC="/usr/bin/gcc-14"
HOSTCC="/usr/bin/gcc"
HOSTCFLAGS="-O2"
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -mapxf -mavx10.1 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure  --host=x86_64-clr-linux-gnu   INSTALL_USER=root \
INSTALL_GROUP=root \
--enable-nls \
--enable-shared \
--enable-static
make  %{?_smp_mflags}
unset CC
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 check || :
cd ../build32;
make VERBOSE=1 check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffunction-sections -fno-lto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707073073
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/attr
cp %{_builddir}/attr-%{version}/doc/COPYING %{buildroot}/usr/share/package-licenses/attr/cade8ab653f461106e2e3ed6fa442c761ee18d9e || :
cp %{_builddir}/attr-%{version}/doc/COPYING.LGPL %{buildroot}/usr/share/package-licenses/attr/1a8a11da70cc41755e50a4aa88f605c4ec1b2f6d || :
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd ../buildavx2/
%make_install_v3
popd
pushd ../buildapx/
%make_install_va
popd
%make_install
%find_lang attr
## Remove excluded files
rm -f %{buildroot}*/usr/share/man/man5/attr.5
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py apx %{buildroot}-va %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/attr
/V3/usr/bin/getfattr
/V3/usr/bin/setfattr
/VA/usr/bin/attr
/VA/usr/bin/getfattr
/VA/usr/bin/setfattr
/usr/bin/attr
/usr/bin/getfattr
/usr/bin/setfattr

%files dev
%defattr(-,root,root,-)
/usr/include/attr/attributes.h
/usr/include/attr/error_context.h
/usr/include/attr/libattr.h
/usr/lib64/libattr.so
/usr/lib64/pkgconfig/libattr.pc
/usr/share/man/man3/attr_get.3
/usr/share/man/man3/attr_getf.3
/usr/share/man/man3/attr_list.3
/usr/share/man/man3/attr_listf.3
/usr/share/man/man3/attr_multi.3
/usr/share/man/man3/attr_multif.3
/usr/share/man/man3/attr_remove.3
/usr/share/man/man3/attr_removef.3
/usr/share/man/man3/attr_set.3
/usr/share/man/man3/attr_setf.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libattr.so
/usr/lib32/pkgconfig/32libattr.pc
/usr/lib32/pkgconfig/libattr.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/attr/*

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libattr.so.1.1.2502
/VA/usr/lib64/libattr.so.1.1.2502
/usr/lib64/libattr.so.1
/usr/lib64/libattr.so.1.1.2502

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libattr.so.1
/usr/lib32/libattr.so.1.1.2502

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/attr/1a8a11da70cc41755e50a4aa88f605c4ec1b2f6d
/usr/share/package-licenses/attr/cade8ab653f461106e2e3ed6fa442c761ee18d9e

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/attr.1
/usr/share/man/man1/getfattr.1
/usr/share/man/man1/setfattr.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libattr.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libattr.a

%files locales -f attr.lang
%defattr(-,root,root,-)

